# Generated by Django 4.0.2 on 2022-03-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0002_aboutme_allicons_homedetails_mycontact_myprogress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='content',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='description_one',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='description_two',
            field=models.TextField(blank=True, null=True),
        ),
    ]
