# Generated by Django 4.0.2 on 2022-03-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0004_servicesoffred_shadow_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedialinks',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='socialmedialinks',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='socialmedialinks',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='socialmedialinks',
            name='mycv_link',
        ),
        migrations.RemoveField(
            model_name='socialmedialinks',
            name='twitter_link',
        ),
        migrations.AddField(
            model_name='socialmedialinks',
            name='social_icon',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
