# Generated by Django 4.0.2 on 2022-03-12 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0005_remove_socialmedialinks_facebook_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedialinks',
            old_name='github_link',
            new_name='link',
        ),
    ]
