# Generated by Django 4.0.2 on 2022-03-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0006_rename_github_link_socialmedialinks_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name_plural': 'AboutMe'},
        ),
        migrations.AlterModelOptions(
            name='homedetails',
            options={'verbose_name_plural': 'HomeDetails'},
        ),
        migrations.AlterModelOptions(
            name='socialmedialinks',
            options={'verbose_name_plural': 'SocialMediaLinks'},
        ),
        migrations.AddField(
            model_name='homedetails',
            name='par_inro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
