# Generated by Django 4.0.2 on 2022-03-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0007_alter_aboutme_options_alter_homedetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedetails',
            name='cv_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homedetails',
            name='hireMe_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
